Repository DexterInd/GoPiGo, pull requests merged in 2018-04, with the labels that each got.

#295 fix - IR receiver on Stretch
  Software/Python/ir_remote_control/README.md
  Software/Python/ir_remote_control/examples/ir_recv_example.py
  Software/Python/ir_remote_control/examples/lirc_example.py
  Software/Python/ir_remote_control/server/di_ir_reader.py
  Software/Python/ir_remote_control/server/install.sh
  Software/Python/ir_remote_control/server/ir_receiver.py
Labels: pending

#298 make IR Receiver in easygopigo Python3 ready
  Software/Python/easygopigo.py
Labels: improvements

#304 flip develop to master branch for DexterOS
  .gitignore
  Setup/install.sh
  Software/Python/easygopigo.py
  Software/Python/ir_remote_control/README.md
  Software/Python/ir_remote_control/examples/ir_recv_example.py
  Software/Python/ir_remote_control/examples/lirc_example.py
  Software/Python/ir_remote_control/server/di_ir_reader.py
  Software/Python/ir_remote_control/server/install.sh
  Software/Python/ir_remote_control/server/ir_receiver.py
  Software/Python/line_follower/scratch_line.py
  Software/Python/setup.py
Labels: additions, improvements

#306 feature - take line follower out
  Setup/install.sh
  Software/Python/easygopigo.py
  Software/Python/line_follower/README.md
  Software/Python/line_follower/__init__.py
  Software/Python/line_follower/basic_example.py
  Software/Python/line_follower/black_line.txt
  Software/Python/line_follower/check_line_sensor.py
  Software/Python/line_follower/line_follow.desktop
  Software/Python/line_follower/line_follow.py
  Software/Python/line_follower/line_follow1.py
  Software/Python/line_follower/line_position.py
  Software/Python/line_follower/line_sensor.py
  Software/Python/line_follower/line_sensor_gui.py
  Software/Python/line_follower/line_threshold_set.py
  Software/Python/line_follower/obconf.png
  Software/Python/line_follower/obconf.xpm
  Software/Python/line_follower/range_line.txt
  Software/Python/line_follower/scratch_line.py
  Software/Python/line_follower/white_line.txt
  Software/Python/setup.py
  Software/Scratch/GoPiGoScratch.py
Labels: improvements
